# version: '3.8'

# services:
#   rasa:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app
#     ports:
#       - 5005:5005
#     environment:
#       - DB_NAME=${DB_NAME}
#       - DB_USER=${DB_USER}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_HOST=${DB_HOST}
#       - DB_PORT=${DB_PORT}
#       - DJ_SECRET_KEY=${DJ_SECRET_KEY}
#       - DEBUG=${DEBUG}
#       - debug_status=${debug_status}
#       - http_secure=${http_secure}
#     command: ["rasa", "run", "--enable-api", "--cors", "*", "--debug"]

#   action_server:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./actions:/app/actions
#     ports:
#       - 5055:5055
#     environment:
#       - DB_NAME=${DB_NAME}
#       - DB_USER=${DB_USER}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_HOST=${DB_HOST}
#       - DB_PORT=${DB_PORT}
#       - DJ_SECRET_KEY=${DJ_SECRET_KEY}
#       - DEBUG=${DEBUG}
#       - debug_status=${debug_status}
#       - http_secure=${http_secure}
#     command: ["/app/entrypoint.sh"]
# version: '3.8'
services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    environment:
      - RASA_ENV=production
    command: ["rasa", "run", "--enable-api", "--cors", "*", "--debug"]
    depends_on:
      - action_server
    networks:
      - rasa_network

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5055:5055
    command: ["/app/entrypoint.sh"]
    networks:
      - rasa_network

networks:
  rasa_network:
